In cadrul Laboratorului 2, scopul meu principal a fost sa transform cerintele functionale ale aplicatiei Personal Investment Dashboard in cifre precise si masurabile de inginerie. Am analizat modul in care utilizatorii interactioneaza cu sistemul si am calculat parametrii de calitate, traficul de cereri si necesarul de stocare pentru trei scari diferite de utilizatori concomitent.
Mai intai, am definit cerintele de calitate folosind formula masuratoare + tinta + conditie de operare. Pentru latenta de citire, am stabilit ca 95% din cereri (p95) trebuie sa raspunda in sub 2000 ms la nivel de server, iar ce depaseste aceasta limita primeste eroare 504 Timeout. La disponibilitate, am impartit timpul in doua ferestre: orele de bursa (Market Hours), unde am setat o tinta de 99.9% uptime (maxim 8 minute de intrerupere pe luna), si in afara orelor de bursa, unde o tinta de 99.0% este suficienta (aproape 6 ore de intrerupere pe luna). Pe partea de consistenta, am impus ca un pret mai vechi de 15 minute fata de furnizor sa fie marcat clar ca "delayed", iar datele lipsa sa fie afisate ca "unavailable", oferind totodata o garantie de Read-Your-Own-Writes pe sesiune pentru modificarile din Watchlist.
In al doilea rand, am calculat traficul de citire in regim stabil (Steady RPS) folosind formula recomandata pentru cele 6 tipuri de interogari. Rezultatele totale de trafic au fost de 79.20 RPS pentru 300 de utilizatori, 792.00 RPS pentru 3.000 de utilizatori si 7.920.00 RPS pentru 30.000 de utilizatori. Analizand datele, am observat ca interogarea pretului (Stock price) domina coplesitor traficul, reprezentand aproximativ 75.76% din totalul cererilor, deoarece 20% din utilizatori fac refresh in fiecare secunda.
Apoi, am estimat traficul de varf de la deschiderea bursei (Market-Open RPS), adaugand peste traficul stabil un flux suplimentar de refresh pentru Overview si Watchlist din partea a 30% din utilizatori intr-un interval de 10 secunde. Dupa ce am adaugat o marja de capacitate de 10% si am rotunjit prin adaos doar la final, am obtinut noile tinte de capacitate: 103 RPS (pt 300 de useri), 1.030 RPS (pt 3.000 de useri) si 10.296 RPS (pt 30.000 de useri).
Pentru estimarea stocarii, am definit clar scope-ul produsului: suport doar pentru piata din SUA (NYSE si NASDAQ), acoperind acțiuni comune, preferentiale si ADR-uri, ceea ce insumeaza aproximativ 8.000 de companii active. Am calculat dimensiunea in octeti pentru fiecare tip de inregistrare si am determinat ca baza de date va ocupa initial aproximativ 618 MB raw (dintre care 615 MB sunt reprezentati de istoricul preturilor pe 5 ani), cu o crestere anuala estimata la aproximativ 123 MB/an.
La final, am analizat potentialele puncte critice (bottlenecks) pentru fiecare calitate:
Pe latenta, ruta de Stock price reprezinta cel mai mare risc de blocaj din cauza volumului imens de cereri (peste 6.000 RPS la scara mare).
Pe consistenta, jobul de sincronizare la 15 minute poate ramane in urma daca nu proceseaza eficient cele 8.000 de acțiuni.
Pe capacitate (throughput), la deschiderea bursei pot aparea blocaje la nivel de baza de date din cauza concurentei dintre cele peste 10.000 RPS de citire si scrierile masive de la furnizor.
Pe disponibilitate, sistemul depinde direct de furnizorul extern de date, o cadere a acestuia afectand direct disponibilitatea datelor live.
